master:
  tags:
    - build
    - deploy
  script:
  - echo 'Build Master'
  - git pull origin master
  - sudo mv . /www/wwwroot/zikri.web.id
  - echo "Cleaning Up"
  - sudo rm -rf /home/gitlab-runner/builds/*
  only:
  - master

development:
  tags:
    - build
    - deploy
  script:
  - echo 'Build Dev'
  - cd /www/wwwroot/dev.zikri.web.id/
  - git stash
  - sudo git pull origin dev
  - echo "Cleaning Up"
  - sudo rm -rf /home/gitlab-runner/builds/*
  only:
  - dev
