master:
  tags:
    - build
    - deploy
  script:
  - echo 'Build Master'
  - cd /www/wwwroot/zikri.web.id/
  - git stash
  - sudo git pull origin master
  only:
  - master

development:
  tags:
    - build
    - deploy
  script:
  - echo 'Build Dev'
  - cd /www/wwwroot/dev.zikri.web.id/
  - git stash
  - sudo git pull origin dev
  only:
  - dev
